### ISSUE TITLE
Any plan to open source your Web Interface?

### ISSUE THREAD

**Issue by yangxuan8282** [arukasio/docker-hub-images#13]
Try app.arukas.io yesterday, it's really easy to use.  Would you open source web ui? So people can use it on other devices like raspberry pi.

**Comment by uzyexe** [comment]
Hi @yangxuan8282, that's a good question!

We are considering making the Arukas Web UI open source.

But there are lots of other tasks to do.
I think it will take more than a year to open source the Web UI.

**Comment by yangxuan8282** [comment]
Great, wait for run it on rpi4 or rpi5.

**Comment by yangxuan8282** [comment]
@uzyexe hi, how did your implement `Endpoint` on app.arukas.io (select a prefix for domain name), like gogs.arukascloud.io, can I do this on my local docker ? It's really convenience. I guess it's something like [SkyDNS](https://github.com/skynetservices/skydns), but not sure.

**Comment by uzyexe** [comment]
@yangxuan8282 It can not be done with Docker alone.

Arukas is [Mesos](http://mesos.apache.org/) and [Marathon](https://mesosphere.github.io/marathon/) based docker container hosting.
Arukas Endpoint is a [Marathon-LB](https://docs.mesosphere.com/1.8/usage/service-discovery/marathon-lb/) based load barancer.

Design:
http://www.slideshare.net/sakura_pr/201608-mesos-studypublic-64721613/42

I wish for it to help you.

**Comment by yangxuan8282** [comment]
hi @uzyexe , thanks for reply. In second link, there is a demo: https://github.com/uzyexe/mesos-marathon-demo
If this demo can provide Endpoint and webui like Arukas?
And do you think this demo is overkill for a single raspberry pi 3( 4× ARM Cortex-A53, 1.2GHz; 1G RAM)
I just need Endpoint and webui, can I strip some service?

**Comment by uzyexe** [comment]
@yangxuan8282 

For the Mesos/Marathon + marathon-lb, recommend a minimum of 8 GB of memory + swap space.
Mesos / marathon is suitable for requirements to host more than 10,000 containers.
However, it does not have a User-Like WebUI. 

If the number of containers you host is less than 100 containers, I think that kubernetes (k8s) is suitable.
Kubernetes has an endpoint loadbalancer called a service router. There will also be [WebUI](https://kubernetes.io/docs/user-guide/ui/).

Or you may consider using [RancherOS](http://rancher.com/rancher-os/).
